routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('project', 'ProjectController');
Route::resource('client', 'ClientController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
    public function workerUsers(){
        return $this->belongsTo('App\User','client_user');
    }
    
    public function projects(){
        return $this->hasMany('App\Project');
    }
    
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use View;
use Auth;
use Validator;
use Session;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (Auth::check()){
            $clients = User::with('clients')->find(Auth::user()->id)->clients;//Client::where('worker_id', Auth::user()->id);
        }else{
            $clients = [];
        }
        return View::make('client.index')
                ->with('clients', $clients);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // validate
        // read more on validation at http://laravel.com/docs/validation
        $rules = array(
            'name'       => 'required',
            'surname'    => 'required',
            'email'      => 'required|email',
            'phone_1'    => 'nullable',
            'phone_2'    => 'nullable',
            'worker_id'  => 'required|numeric'
        );
        $validator = Validator::make(Input::all(), $rules);

        // process the login
        if ($validator->fails() || !Auth::check()) {
            return Redirect::to('client/create')
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        } else {
            // store
            $client = new Client;
            $client->name       = Input::get('name');
            $client->surname    = Input::get('surname');
            $client->email      = Input::get('email');
            $client->phone_n1    = Input::get('phone_1');
            $client->phone_n2    = Input::get('phone_2');
            $client->worker_id  = Input::get('worker_id');
            if (Auth::user()->id != $client->worker_id){
                Session::flash('message', 'Non puoi registrare un utente come fossi qualcun altro!');
                return Redirect::to('client');
            }
            $client->save();

            // redirect
            Session::flash('message', 'Cliente registrato con successo');
            return Redirect::to('client');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        // get the client
        $client = Client::find($client->id);

        // show the view and pass the client to it
        return View::make('client.show')
            ->with('client', $client);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        
        // get the client
        $client = Client::find($client->id);

        return View::make('client.edit')
            ->with('client', $client);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $rules = array(
            'name'       => 'required',
            'surname'    => 'required',
            'email'      => 'required|email',
            'phone_1'    => 'nullable',
            'phone_2'    => 'nullable'
        );
        $validator = Validator::make(Input::all(), $rules);

        // process the login
        if ($validator->fails() || !Auth::check()) {
            return Redirect::to('client/' . $client->id . '/edit')
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        } else {
            // store
            $client = Client::find($client->id);
            $client->name       = Input::get('name');
            $client->surname    = Input::get('surname');
            $client->email      = Input::get('email');
            $client->phone_n1    = Input::get('phone_1');
            $client->phone_n2    = Input::get('phone_2');
            if (Auth::user()->id != $client->worker_id){
                Session::flash('message', 'Non puoi modificare un cliente non tuo!');
                return Redirect::to('client/' . $client->id . '/edit');
            }
            $client->save();

            // redirect
            Session::flash('message', 'Cliente modificato con successo');
            return Redirect::to('client');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        // delete
        $client = client::find($client->id);
        $client->delete();

        // redirect
        Session::flash('message', 'Successfully deleted the client!');
        return Redirect::to('client');
    }
}

resources/views/client/create.blade.php
@extends('layouts.base')

@section('content')
<div class="container">

    <!-- if there are creation errors, they will show here -->
    <!-- HTML::ul($errors->all()) not more well supported in laravel -->
    
    @guest
        <!-- Is not possible create something without to be a registered User -->
        <div class="panel panel-danger">
          <div class="panel-heading">Solo per utenti registrati!</div>
          <div class="panel-body">
            Se vuoi registrare un cliente devi prima registrarti o fare il login tu!
            <br/>
            <a href="{{ URL::to('login') }}" class="card btn btn-link">Login</a> <a href="{{ URL::to('register') }}" class="card btn btn-link">Register</a>
          </div>
        </div>
    
    @else
        @if(isset($errors) && count($errors)>0)
        <div class="row">
            <div class="alert alert-danger">
                The following forms are <strong>incorrect</strong>:
                <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            </div>
        </div>
        @endif
        <form method="POST" action="/client">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-4 col-offset-1 form-group">
                    <label name="name_label">Nome</label>
                    <input type="text" name="name"></input> 
                </div>
                <div class="col-md-4 col-offset-1 form-group">
                    <label name="surname_label">Congome</label>
                    <input type="text" name="surname"></input> 
                </div>
            </div>

            <div class="row">
            <div class="form-group">
                <label name="email_label">Email</label>
                <input type="email" name="email"></input> 
            </div>
            </div>
            
            <div class="row">
                <div class="col-md-4 col-offset-1 form-group">
                    <label name="phone_1_label">Numero °1</label>
                    <input type="text" name="phone_1"></input> 
                </div>
                <div class="col-md-4 col-offset-1 form-group">    
                    <label name="phone_2_label">Numero °2</label>
                    <input type="text" name="phone_2"></input> 
                </div>
            </div>
            
            <input type="hidden" name="worker_id" value="{{ Auth::user()->id }}"/>
            
            <input type="submit"/>

            <script>
            </script>
        </form>
    @endguest
    
</div>
@endsection

resources/views/client/edit.blade.php
@extends('layouts.base')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Editing {{ $client->name." ".$client->surname }} info</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('client.update',$client->id) }}" required>
                        {{ method_field('PUT') }}
                        {{ csrf_field() }}

                        <!-- Name -->
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nome</label>

                            <div class="col-md-6">
                                <input  type="text" class="form-control" name="name" value="{{ $client->name }}" required>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <!-- Surname -->
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="surname" class="col-md-4 control-label">Surname</label>

                            <div class="col-md-6">
                                <input  type="text" class="form-control" name="surname" value="{{ $client->surname }}">

                                @if ($errors->has('surname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('surname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <!-- Email input -->
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ $client->email }}" required autofocus>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <!-- First Telephone number -->
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="phone_1" class="col-md-4 control-label">Tel. n°1</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="phone_1" value="{{ $client->phone_n1 }}">

                                @if ($errors->has('phone_1'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone_1') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <!-- Second Telephone number -->
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="phone_2" class="col-md-4 control-label">Tel. n°2</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="phone_2" value="{{ $client->phone_n2 }}">

                                @if ($errors->has('phone_2'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone_2') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    EDIT
                                </button>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/client/index.blade.php
@extends('layouts.base')

@section('content')
<div class="container">
    @foreach ($clients as $key=>$value)
    <div class="row">
        <div class="card panel panel-info">
            <a href="{{ URL::to('client/'.$value->id) }}">
                <div class="panel-heading">
                    <div class="col-md-10 col-offset-1">
                        <h4><strong> {{ $value->name.' '.$value->surname }} </strong></h4>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4 col-offset-1">
                            <strong>Email:</strong> {{ $value->email }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-offset-1">
                            <strong>Tel. n°1</strong>: {{ $value->phone_n1 }}
                        </div>
                        <div class="col-md-4 col-offset-1">
                            <strong>Tel. n°2:</strong> {{ $value->phone_n2 }}
                        </div>
                    </div>
                    <div class="container"></div>
                </div>
            </a>
            <!-- Button to delete the client -->
            <form method="POST" action="{{ route('client.destroy', $value->id) }}">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button type="submit" class="btn btn-primary floating-x">
                    Elimina
                </button>
            </form>
        </div>        
    </div>
    @endforeach
    
    <!-- Insert JQuery to answer if you want delete the client -->
</div>
<div class="container">
    <div class="col-md-12">
        <a href="{{ URL::to('client/create') }}" class="btn btn-info" >Register new Client</a>
    </div>
</div>
@endsection

resources/views/client/show.blade.php
@extends('layouts.base')

@section('content')
<div class="container">
    <h1>Showing <strong>{{ $client->name." ".$client->surname }}</strong></h1>

    <div class="jumbotron text-center">
        <h2>{{ $client->name." ".$client->surname }}</h2>
        <p>
            <strong>Email:</strong> {{ $client->email }}<br>
            <strong>Tel. n°1:</strong> {{ $client->phone_n1 }}<br/>
            <strong>Tel. n°2:</strong> {{ $client->phone_n2 }}<br/>
        </p>
        <a class="btn btn-primary " href="{{ route('client.edit',$client->id) }}">Edit client</a>
        <form method="POST" action="{{ route('client.destroy', $client->id) }}">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            <button type="submit" class="btn btn-primary">
                Elimina
            </button>
        </form>
    </div>
</div>
@endsection